namespace :coupon do
  desc "Initialize: import city data."
  task :import_city  => :environment do
    @all_str=<<-EOF
安徽(1)-明光-mingguang-mg
安徽(1)-黄山-huangshan-hs
安徽(1)-桐城-tongcheng-tc
安徽(1)-安庆-anqing-aq
安徽(1)-合肥-gefei-hf
安徽(1)-宣城-xuancheng-xc
安徽(1)-铜陵-tongling-tl
安徽(1)-淮南-huainan-hn
安徽(1)-滁州-chuzhou-cz
安徽(1)-马鞍山-maanshan-mas
安徽(1)-芜湖-wuhu-wh
安徽(1)-阜阳-fuyang-fy
安徽(1)-天长-tianchang-tc
安徽(1)-蚌埠-bengbu-bb
安徽(1)-宁国-ningguo-ng
安徽(1)-巢湖-chaohu-ch
安徽(1)-六安-liuan-la
安徽(1)-池州-chizhou-cz
北京(2)-北京-beijing-bj
重庆(3)-达州-dazhou-dz
重庆(3)-永川-yongchuan-yc
重庆(3)-万州-wanzhou-wz
重庆(3)-涪陵-fuling-fl
重庆(3)-重庆-chongqing-zq
重庆(3)-长寿-changshou-cs
重庆(3)-广安-guangan-ga
福建(4)-泉州-quanzhou-qz
福建(4)-南平-nanping-np
福建(4)-三明-sanming-sm
福建(4)-福鼎-fuding-fd
福建(4)-漳州-zhangzhou-zz
福建(4)-福州-fuzhou-fz
福建(4)-莆田-putian-pt
福建(4)-厦门-xiamen-xm
福建(4)-长乐-changle-cl
福建(4)-宁德-ningde-nd
福建(4)-石狮-shishi-ss
福建(4)-龙岩-longyan-ly
福建(4)-晋江-jinjiang-jj
福建(4)-福清-fuqing-fq
甘肃(5)-兰州-lanzhou-lz
甘肃(5)-酒泉-jiuquan-jq
甘肃(5)-天水-tianshui-ts
广东(6)-东莞-dongguan-dg
广东(6)-深圳-shenzhen-sc
广东(6)-广州-guangzhou-gz
广东(6)-珠海-zhuhai-zh
广西(7)-桂林-guilin-gl
广西(7)-柳州-liuzhou-lz
广西(7)-南宁-nanning-nn
广西(7)-玉林-yulin-yl
贵州(8)-毕节-bijie-bj
贵州(8)-遵义-zunyi-zy
贵州(8)-贵阳-guiyang-gy
海南(9)-海口-haikou-hk
河北(10)-张家口-zhangjiakou-zjk
河北(10)-衡水-hengshui-hs
河北(10)-涿州-zhuozhou-zz
河北(10)-天津-tianjin-tj
河北(10)-廊坊-langfang-lf
河北(10)-承德-chengde-cd
河北(10)-沧州-cangzhou-cz
河北(10)-唐山-tangshan-ts
河北(10)-邢台-xingtai-xt
河北(10)-保定-baoding-bd
河北(10)-石家庄-shijiazhuang-sjz
河北(10)-霸州-bazhou-bz
河北(10)-邯郸-handan-hd
黑龙江(11)-齐齐哈尔-qiqihaer-qqhe
黑龙江(11)-哈尔滨-haerbin-heb
河南(12)-南阳-nanyang-ny
河南(12)-信阳-xinyang-xy
河南(12)-许昌-xuchang-xc
河南(12)-洛阳-luoyang-ly
河南(12)-商丘-shangqiu-sq
河南(12)-焦作-jiaozuo-jz
河南(12)-郑州-zhengzhou-zz
河南(12)-漯河-tahe-lh
河南(12)-三门峡-sanmenxia-smx
河南(12)-濮阳-puyang-py
河南(12)-周口-zhoukou-zk
河南(12)-开封-kaifeng-kf
河南(12)-新乡-xinxiang-xx
湖北(13)-鄂州-ezhou-ez
湖北(13)-天门-tianmen-tm
湖北(13)-襄樊-xiangfan-xf
湖北(13)-十堰-shiyan-sy
湖北(13)-钟祥-zhongxiang-zx
湖北(13)-荆州-jingzhou-jz
湖北(13)-黄冈-huanggang-hg
湖北(13)-宜昌-yichang-yc
湖北(13)-武汉-wuhan-wh
湖北(13)-仙桃-xiantao-xt
湖北(13)-恩施-enshi-es
湖北(13)-黄石-huangshi-hs
湖北(13)-监利-jianli-jl
湖北(13)-孝感-xiaogan-xg
湖北(13)-荆门-jingmen-jm
湖南(14)-长沙-changsha-cs
湖南(14)-株洲-zhuzhou-zz
湖南(14)-衡阳-hengyang-hy
湖南(14)-益阳-yiyang-yy
湖南(14)-岳阳-yueyang-yy
湖南(14)-永州-yongzhou-yz
湖南(14)-张家界-zhangjiajie-zjj
湖南(14)-怀化-huaihua-hh
湖南(14)-浏阳-liuyang-ly
湖南(14)-娄底-loude-ld
湖南(14)-湘潭-xiangtan-xt
湖南(14)-常德-changde-cd
江苏(15)-仪征-yizheng-yz
江苏(15)-镇江-zhenjiang-zj
江苏(15)-如皋-rugao-rg
江苏(15)-邳州-pizhou-pz
江苏(15)-丹阳-danyang-dy
江苏(15)-常州-changzhou-cz
江苏(15)-如东-rudong-rd
江苏(15)-新沂-xinyi-xy
江苏(15)-徐州-xuzhou-xz
江苏(15)-句容-jurong-jr
江苏(15)-吴江-wujiang-wj
江苏(15)-连云港-lianyungang-lyg
江苏(15)-启东-qidong-qd
江苏(15)-金坛-jintan-jt
江苏(15)-溧阳-liyang-ly
江苏(15)-东台-dongtai-dt
江苏(15)-张家港-zhangjiagang-zjg
江苏(15)-盐城-yancheng-yc
江苏(15)-无锡-wuxi-wx
江苏(15)-苏州-suzhou-sz
江苏(15)-靖江-jingjiang-jj
江苏(15)-江都-jiangdou-jd
江苏(15)-姜堰-jiangyan-jy
江苏(15)-海门-haimen-hm
江苏(15)-兴化-xinghua-xh
江苏(15)-高邮-gaoyou-gy
江苏(15)-泰兴-taixing-tx
江苏(15)-南通-nantong-nt
江苏(15)-扬中-yangzhong-yz
江苏(15)-淮安-huaian-ha
江苏(15)-昆山-kunshan-ks
江苏(15)-宜兴-yixing-yx
江西(16)-赣州-ganzhou-gz
江西(16)-新余-xinyu-xy
江西(16)-南昌-nanchang-nc
江西(16)-宜春-yichun-yc
江西(16)-抚州-fuzhou1-fz
江西(16)-九江-jiujiang-jj
江西(16)-上饶-shangrao-sr
江西(16)-萍乡-pingxiang-px
江西(16)-景德镇-jingdezhen-jdz
吉林(17)-长春-changchun-cc
辽宁(18)-沈阳-shenyang-sy
辽宁(18)-本溪-benxi-bx
辽宁(18)-营口-yingkou-yk
辽宁(18)-锦州-jinzhou-jz
辽宁(18)-抚顺-fushun-fs
辽宁(18)-大连-dalian-dl
内蒙(19)-呼和浩特-huhehaote-hhht
内蒙(19)-鄂尔多斯-eerduosi-eeds
内蒙(19)-呼伦贝尔/海拉尔-hulunbeierhailaer-hlbehle
内蒙(19)-包头-baotou-bt
宁夏(20)-银川-yinchuan-yc
青海(21)-西宁-xining-xn
山东(22)-青岛-qingdao-qd
山东(22)-菏泽-heze-hz
山东(22)-淄博-zibo-zb
山东(22)-临沂-linyi-ly
山东(22)-烟台-yantai-yt
山东(22)-即墨-jimo-jm
山东(22)-东营-dongying-dy
山东(22)-济南-jinan-jn
陕西(24)-宝鸡-baoji-bj
陕西(24)-汉中-hanzhong-hz
陕西(24)-咸阳-xianyang-xy
陕西(24)-延安-yanan-ya
陕西(24)-西安-xian-xa
陕西(24)-安康-ankang-ak
陕西(24)-渭南-weinan-wn
山西(25)-太原-taiyuan-ty
山西(25)-阳泉-yangquan-yq
山西(25)-临汾-linfen-lf
山西(25)-长治-changzhi-cz
山西(25)-大同-datong-dt
山西(25)-晋城-jincheng-jc
山西(25)-运城-yuncheng-yc
山西(25)-侯马-houma-hm
四川(26)-宜宾-yibin-yb
四川(26)-遂宁-suining-sn
四川(26)-乐山-yueshan-ls
四川(26)-眉山-meishan-ms
四川(26)-内江-neijiang-nj
四川(26)-江油-jiangyou-jy
四川(26)-泸州-luzhou-lz
四川(26)-巴中-bazhong-bz
四川(26)-广汉-guanghan-gh
四川(26)-南充-nanchong-nc
四川(26)-成都-chengdou-cd
四川(26)-自贡-zigong-zg
四川(26)-广元-guangyuan-gy
四川(26)-资阳-ziyang-zy
四川(26)-邛崃-qionglai-ql
四川(26)-绵阳-mianyang-my
四川(26)-德阳-deyang-dy
新疆(27)-库尔勒-kuerle-kel
新疆(27)-乌鲁木齐-wulumuqi-wlmq
新疆(27)-阿克苏-akesu-aks
云南(28)-昆明-kunming-km
浙江(29)-萧山-xiaoshan-xs
浙江(29)-嵊州-shengzhou-cz
浙江(29)-兰溪-lanxi-lx
浙江(29)-宁波-ningbo-nb
浙江(29)-奉化-fenghua-fh
浙江(29)-海宁-haining-hn
浙江(29)-永康-yongkang-yk
浙江(29)-金华-jinhua-jh
浙江(29)-瑞安-ruian-ra
浙江(29)-绍兴-shaoxing-sx
浙江(29)-乐清-yueqing-lq
浙江(29)-湖州-huzhou-hz
浙江(29)-杭州-hangzhou-hz
浙江(29)-台州-taizhou-tz
浙江(29)-嘉兴-jiaxing-jx
浙江(29)-诸暨-zhuji-zj
浙江(29)-平湖-pinghu-ph
浙江(29)-衢州-quzhou-qz
浙江(29)-慈溪-cixi-cx
浙江(29)-义乌-yiwu-yw
浙江(29)-丽水-lishui-ls
浙江(29)-桐乡-tongxiang-tx
浙江(29)-温州-wenzhou-wz
浙江(29)-舟山-zhoushan-zs
浙江(29)-临安-linan-la
浙江(29)-临海-linhai-lh
浙江(29)-东阳-dongyang-dy
EOF

    items = @all_str.split("\n")
    items.each do |item|
      prov, name, pinyin, code_name = item.split("-")
      province_id = prov.scan(/.[^\(]*\)/).join.gsub(/[\(|\)]/, '')
      province = Province.find(province_id)
      province.cities.create!(:name => name, :pinyin => pinyin, :code_name => code_name)
    end
    puts "ok"
  end


end
